### ISSUE TITLE
Use R.utils in place of archive?

### ISSUE THREAD

**Issue by cboettig** [ropensci/bowerbird#33]
I haven't looked deeply enough to be sure this would work, but just an idea.  The situation with `archive`(https://github.com/jimhester/archive/issues/28) does seem rather tragic, but for bowerbird to be CRAN-compatible, perhaps you could use the extended compression utilities in https://github.com/HenrikBengtsson/R.utils instead?

**Comment by raymondben** [comment]
Unfortunately `archive` is needed purely for handling `.Z` files, which `R.utils` doesn't support.

**Comment by cboettig** [comment]
Ha! And I'd of thought good ol unix `compress` was something that base R would have built right in.  Given that LZW is arguably a bit of a legacy format today, maybe `archive` could be made an opt-in rather than a hard dependency as well?

**Comment by raymondben** [comment]
`archive` is a Suggested package only, so not much more to do here I don't think
